INSERT INTO courses (course_name) VALUES ('History');
INSERT INTO courses (course_name) VALUES ('Philosophy');
INSERT INTO courses (course_name) VALUES ('Sociology');
INSERT INTO courses (course_name) VALUES ('Political science');
INSERT INTO courses (course_name) VALUES ('Culture');
INSERT INTO courses (course_name) VALUES ('Biology');
INSERT INTO courses (course_name) VALUES ('Chemistry');
INSERT INTO courses (course_name) VALUES ('Mathematics');
INSERT INTO courses (course_name) VALUES ('Physics');
INSERT INTO courses (course_name) VALUES ('Geometry');
COMMIT;
